steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rpg-tools:$SHORT_SHA', '.']
timeout: 2000s
images:
  - 'gcr.io/$PROJECT_ID/rpg-tools:$SHORT_SHA'
options:
  machineType: E2_HIGHCPU_32
  logging: CLOUD_LOGGING_ONLY
